import Head from "next/head";

import Header from "/components/Header";
import HeroSection from "/components/HeroSection/HeroSection";
import SponsorsSection from "../components/SponsorsSection";
import ConferenceTopicsSection from "/components/ConferenceTopicsSection";
import Quote from "/components/Quote";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto">
        <Header className="mb-8" />
        <HeroSection />
        <SponsorsSection className="mt-[86px]" />
        <div className="w-full border-t-[1px] text-lightgray mt-[145px]" />
        <ConferenceTopicsSection className="mt-[144px]" />
        <Quote className="w-[950px] mb-10" author="Steve Jobs, Apple">
          We belief was that if we kept putting great products in front of
          customers, they would continue to open their wallets.
        </Quote>
      </main>
    </>
  );
}
